version: '3'
name: mongo-sharding-repl
services:
  configSrv:
    image: mongo:8.0.13
    container_name: configSrv 
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",  
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_primary:
    image: mongo:8.0.13
    container_name: shard1_primary
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.20
    volumes:
      - shard1-primary-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_secondary1:
    image: mongo:8.0.13
    container_name: shard1_secondary1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.21
    volumes:
      - shard1-secondary1-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_secondary2:
    image: mongo:8.0.13
    container_name: shard1_secondary2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.22
    volumes:
      - shard1-secondary2-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_primary:
    image: mongo:8.0.13
    container_name: shard2_primary
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.30
    volumes:
      - shard2-primary-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2", 
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_secondary1:
    image: mongo:8.0.13
    container_name: shard2_secondary1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.31
    volumes:
      - shard2-secondary1-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2", 
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_secondary2:
    image: mongo:8.0.13
    container_name: shard2_secondary2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.32
    volumes:
      - shard2-secondary2-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2", 
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  mongos_router:
    image: mongo:8.0.13
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos", 
        "--configdb", 
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    depends_on:
      - configSrv
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:
  shard1-primary-data:
  shard1-secondary1-data:
  shard1-secondary2-data:
  shard2-primary-data:
  shard2-secondary1-data:
  shard2-secondary2-data: